version: '3.8'

services:
  app:
    image: openjdk:17
    container_name: app
    working_dir: /app
    volumes:
      - .:/app
    command: ["./mvnw", "spring-boot:run"]
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cotacao
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql
    networks:
      - minha-rede  # Adicionado aqui
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cotacao
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./init_sql:/docker-entrypoint-initdb.d/
    networks:
      - minha-rede  # Adicionado aqui

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - minha-rede  # Adicionado aqui

  servicos-externos:
    image: python:3.9
    container_name: servicos-externos
    volumes:
      - ./mock_services:/app
    working_dir: /app
    ports:
      - "9091:9091"
    command: ["python", "mock_api.py"]
    networks:
      - minha-rede  # Adicionado aqui

networks:
  minha-rede:
    driver: bridge