# --- application-mock.properties ---

# 1. Configuração do Banco de Dados (MOCK)
# Sobrepõe o PostgreSQL e usa o H2 em memória
spring.datasource.url=jdbc:h2:mem:cotacoesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria o schema do zero toda vez que a app iniciar
spring.jpa.hibernate.ddl-auto=create-drop

# 2. Desabilitar o Kafka (MOCK)
# Impede que os 'listeners' tentem se conectar a um broker
spring.kafka.listener.auto-startup=false