{
  "type": "record",
  "name": "CotacaoRequest",
  "namespace": "com.realizacontacoes.realizacontacoes.avro",
  "fields": [
    {"name": "id", "type": "long"},
    {"name": "product_id", "type": "string"},
    {"name": "offer_id", "type": "string"},
    {"name": "category", "type": "string", "default": ""},
    {"name": "created_at", "type": "string", "default": ""},
    {"name": "updated_at", "type": "string", "default": ""},
    {"name": "total_monthly_premium_amount", "type": "double", "default": 0.0},
    {"name": "total_coverage_amount", "type": "double", "default": 0.0},
    {"name": "coverages", "type": {"type": "map", "values": "double"}, "default": {}},
    {
      "name": "customer",
      "type": {
        "type": "record",
        "name": "Customer",
        "fields": [
          {"name": "document_number", "type": "string", "default": ""},
          {"name": "name", "type": "string", "default": ""},
          {"name": "type", "type": "string", "default": ""},
          {"name": "gender", "type": "string", "default": ""},
          {"name": "date_of_birth", "type": "string", "default": ""},
          {"name": "email", "type": "string", "default": ""},
          {"name": "phone_number", "type": "long", "default": 0}
        ]
      },
      "default": {}
    }
  ]
}
